import { getMemoryFiles } from "@/lib/workspace";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { FileText, Hash, Clock, ExternalLink, Archive, Folder } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function DocsPage() {
  const memoryFiles = await getMemoryFiles();

  // Categorize workspace files
  const staticDocs = [
    { name: "AGENTS.md", path: "/home/mathew/.openclaw/workspace/AGENTS.md", type: "system", category: "Static" },
    { name: "SOUL.md", path: "/home/mathew/.openclaw/workspace/SOUL.md", type: "personality", category: "Static" },
    { name: "USER.md", path: "/home/mathew/.openclaw/workspace/USER.md", type: "profile", category: "Static" },
    { name: "IDENTITY.md", path: "/home/mathew/.openclaw/workspace/IDENTITY.md", type: "identity", category: "Static" },
    { name: "MEMORY.md", path: "/home/mathew/.openclaw/workspace/MEMORY.md", type: "memory", category: "Static" },
    { name: "HEARTBEAT.md", path: "/home/mathew/.openclaw/workspace/HEARTBEAT.md", type: "config", category: "Static" },
    { name: "TOOLS.md", path: "/home/mathew/.openclaw/workspace/TOOLS.md", type: "config", category: "Static" },
    { name: "SPEC.md", path: "/home/mathew/.openclaw/workspace/SPEC.md", type: "project", category: "Static" },
    { name: "DREAMS.md", path: "/home/mathew/.openclaw/workspace/DREAMS.md", type: "roadmap", category: "Static" },
  ];

  // Auto-generated reports (from /api/docs/generate)
  const autoGeneratedReports = [
    { name: "Weekly Report (2026-05-03)", type: "weekly", category: "Auto-Generated", date: "2026-05-03" },
  ];

  const typeColors: Record<string, { border: string; text: string; icon: string }> = {
    system: { border: "border-amber/30", text: "text-amber", icon: "⚙️" },
    personality: { border: "border-violet/30", text: "text-violet", icon: "🧠" },
    profile: { border: "border-moss/30", text: "text-moss", icon: "👤" },
    identity: { border: "border-moss/30", text: "text-moss", icon: "🔮" },
    memory: { border: "border-violet/30", text: "text-violet", icon: "📡" },
    config: { border: "border-text-muted/30", text: "text-text-muted", icon: "🔧" },
    project: { border: "border-moss/30", text: "text-moss", icon: "🚀" },
    roadmap: { border: "border-amber/30", text: "text-amber", icon: "🗺️" },
    weekly: { border: "border-violet/30", text: "text-violet", icon: "📊" },
    daily: { border: "border-violet/30", text: "text-violet", icon: "📝" },
  };

  return (
    <div className="p-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <h1 className="text-2xl font-semibold text-text-primary">Docs</h1>
          <Badge variant="outline" className="border-moss text-moss font-mono text-xs">
            {staticDocs.length + memoryFiles.length + autoGeneratedReports.length} INDEXED
          </Badge>
        </div>
        <p className="text-text-secondary text-sm">
          Agent-generated documentation and workspace files
        </p>
      </div>

      {/* Auto-Generated Reports - First as priority */}
      {autoGeneratedReports.length > 0 && (
        <div className="mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Archive className="w-4 h-4 text-violet" />
            <h2 className="text-sm font-medium text-text-secondary uppercase tracking-wider">
              Auto-Generated Reports
            </h2>
            <Badge variant="secondary" className="bg-violet/10 text-violet border-violet/20 font-mono text-xs">
              {autoGeneratedReports.length}
            </Badge>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {autoGeneratedReports.map((report) => (
              <Card
                key={report.name}
                className="bg-obsidian-light border-violet/30 p-4 rounded-xl glow-violet hover:border-violet/60 transition-colors group cursor-pointer"
              >
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-lg border border-violet/30 flex items-center justify-center bg-violet/10">
                    <span className="text-lg">{typeColors[report.type]?.icon || "📊"}</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-text-primary text-sm font-medium group-hover:text-violet transition-colors">
                      {report.name}
                    </p>
                    <Badge
                      variant="secondary"
                      className="mt-1 font-mono text-xs bg-violet/10 text-violet border-violet/20"
                    >
                      {report.category}
                    </Badge>
                    <p className="text-text-muted text-xs mt-1 font-mono">
                      Generated: {report.date}
                    </p>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* Static Docs */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-4">
          <Folder className="w-4 h-4 text-moss" />
          <h2 className="text-sm font-medium text-text-secondary uppercase tracking-wider">
            Static Docs
          </h2>
          <Badge variant="secondary" className="bg-moss/10 text-moss border-moss/20 font-mono text-xs">
            {staticDocs.length}
          </Badge>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {staticDocs.map((file) => (
            <Card
              key={file.name}
              className="bg-obsidian-light border-border p-4 rounded-xl hover:border-border/80 transition-colors group"
            >
              <div className="flex items-start gap-3">
                <div className={`w-8 h-8 rounded-lg border ${typeColors[file.type]?.border || "border-border"} flex items-center justify-center`}>
                  <span className={`text-sm ${typeColors[file.type]?.text || "text-text-muted"}`}>
                    {typeColors[file.type]?.icon || "📄"}
                  </span>
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-text-primary text-sm font-medium group-hover:text-moss transition-colors">
                    {file.name}
                  </p>
                  <Badge
                    variant="secondary"
                    className={`mt-1 font-mono text-xs ${typeColors[file.type]?.border || "border-border"} ${typeColors[file.type]?.text || "text-text-muted"}`}
                  >
                    {file.type}
                  </Badge>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>

      {/* Daily Logs */}
      <div>
        <div className="flex items-center gap-2 mb-4">
          <Clock className="w-4 h-4 text-violet" />
          <h2 className="text-sm font-medium text-text-secondary uppercase tracking-wider">
            Daily Logs
          </h2>
          <Badge variant="secondary" className="bg-violet/10 text-violet border-violet/20 font-mono text-xs">
            {memoryFiles.length}
          </Badge>
        </div>
        {memoryFiles.length === 0 ? (
          <ZenEmptyState />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {memoryFiles.map((file) => (
              <Card
                key={file.date}
                className="bg-obsidian-light border-border p-4 rounded-xl glow-violet hover:border-violet/50 transition-colors"
              >
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 rounded-lg border border-violet/30 flex items-center justify-center">
                    <Clock className="w-4 h-4 text-violet" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-text-primary text-sm font-medium font-mono">
                      {file.date}
                    </p>
                    <p className="text-text-muted text-xs truncate">
                      {getFirstLine(file.content)}
                    </p>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function getFirstLine(content: string): string {
  const lines = content.split("\n").filter((l) => l.trim());
  const firstMeaningful = lines.find((l) => !l.startsWith("#"));
  return firstMeaningful?.slice(0, 50) || "Empty log";
}

function ZenEmptyState() {
  return (
    <Card className="bg-obsidian-light border-border/50 p-8 rounded-xl mist-overlay">
      <div className="text-center">
        <FileText className="w-6 h-6 text-violet/30 mx-auto mb-2" />
        <p className="text-text-muted text-xs font-mono">
          No daily logs yet...
        </p>
      </div>
    </Card>
  );
}