import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const WORKSPACE = process.env.OPENCLAW_WORKSPACE || "/home/mathew/.openclaw/workspace";

interface TaskSummary {
  date: string;
  completed: string[];
  pending: string[];
  total: number;
}

function parseTasksFromContent(content: string): { completed: string[]; pending: string[] } {
  const lines = content.split("\n");
  const completed: string[] = [];
  const pending: string[] = [];
  let inTasks = false;

  for (const line of lines) {
    if (line.match(/^##\s+Tasks/i)) {
      inTasks = true;
      continue;
    }
    if (line.match(/^##\s+/) && inTasks) break;
    if (inTasks) {
      const doneMatch = line.match(/^-\s+\[x\]\s+(.+)/i);
      const pendingMatch = line.match(/^-\s+\[\s]\s+(.+)/i);
      if (doneMatch) completed.push(doneMatch[1].trim());
      else if (pendingMatch) pending.push(pendingMatch[1].trim());
    }
  }

  return { completed, pending };
}

function getLastNDays(n: number): string[] {
  const dates: string[] = [];
  for (let i = 1; i <= n; i++) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    dates.push(d.toISOString().split("T")[0]);
  }
  return dates;
}

function generateWeeklyReport(taskSummaries: TaskSummary[]): string {
  const totalTasks = taskSummaries.reduce((sum, t) => sum + t.total, 0);
  const totalCompleted = taskSummaries.reduce((sum, t) => sum + t.completed.length, 0);
  const totalPending = taskSummaries.reduce((sum, t) => sum + t.pending.length, 0);

  const allCompleted = taskSummaries.flatMap((t) => t.completed);
  const allPending = taskSummaries.flatMap((t) => t.pending);
  
  // Dedupe completed tasks
  const uniqueCompleted = [...new Set(allCompleted)];
  const uniquePending = [...new Set(allPending)];

  let report = `# Weekly Agent Report\n\n`;
  report += `Generated: ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}\n\n`;

  report += `## Summary\n\n`;
  report += `- **Total Tasks Tracked:** ${totalTasks}\n`;
  report += `- **Completed:** ${totalCompleted} (${totalTasks > 0 ? Math.round((totalCompleted / totalTasks) * 100) : 0}%)\n`;
  report += `- **Pending:** ${totalPending}\n\n`;

  report += `## Focus Areas This Week\n\n`;
  if (uniqueCompleted.length > 0) {
    report += `### Completed\n\n`;
    uniqueCompleted.forEach((task) => {
      report += `- ~~${task}~~ ✓\n`;
    });
    report += `\n`;
  }

  if (uniquePending.length > 0) {
    report += `### Still In Progress\n\n`;
    uniquePending.forEach((task) => {
      report += `- ${task}\n`;
    });
    report += `\n`;
  }

  report += `## Daily Breakdown\n\n`;
  taskSummaries.forEach((day) => {
    report += `### ${day.date}\n\n`;
    if (day.completed.length > 0) {
      report += `**Done:** ${day.completed.length}\n`;
      day.completed.forEach((t) => {
        report += `- ~~${t}~~\n`;
      });
    }
    if (day.pending.length > 0) {
      report += `**Pending:** ${day.pending.length}\n`;
      day.pending.forEach((t) => {
        report += `- ${t}\n`;
      });
    }
    if (day.completed.length === 0 && day.pending.length === 0) {
      report += `No tasks recorded.\n`;
    }
    report += `\n`;
  });

  report += `---\n\n*Generated by KATZEN Agent Dashboard*\n`;

  return report;
}

export async function GET() {
  try {
    const days = 7; // Last 7 days
    const dates = getLastNDays(days);
    const memoryDir = path.join(WORKSPACE, "memory");
    const docsDir = path.join(WORKSPACE, "docs");

    // Ensure docs directory exists
    if (!fs.existsSync(docsDir)) {
      fs.mkdirSync(docsDir, { recursive: true });
    }

    const taskSummaries: TaskSummary[] = [];
    const recentTasks: string[] = [];
    const recentPending: string[] = [];

    for (const date of dates) {
      const filePath = path.join(memoryDir, `${date}.md`);
      if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, "utf-8");
        const { completed, pending } = parseTasksFromContent(content);
        taskSummaries.push({
          date,
          completed,
          pending,
          total: completed.length + pending.length,
        });
        
        // Track recent unique tasks
        completed.forEach((t) => {
          if (!recentTasks.includes(t)) recentTasks.push(t);
        });
        pending.forEach((t) => {
          if (!recentPending.includes(t)) recentPending.push(t);
        });
      }
    }

    // Generate report
    const report = generateWeeklyReport(taskSummaries);

    // Write to docs
    const today = new Date().toISOString().split("T")[0];
    const filename = `weekly-report-${today}.md`;
    const filePath = path.join(docsDir, filename);
    fs.writeFileSync(filePath, report, "utf-8");

    return NextResponse.json({
      success: true,
      filename,
      path: filePath,
      summary: {
        daysCovered: taskSummaries.length,
        totalTasks: taskSummaries.reduce((s, t) => s + t.total, 0),
        completedCount: recentTasks.length,
        pendingCount: recentPending.length,
      },
      toastMessage: `[KITTY]: New documentation indexed: ${filename}`,
    });
  } catch (error) {
    console.error("Failed to generate report:", error);
    return NextResponse.json(
      { error: "Failed to generate weekly report" },
      { status: 500 }
    );
  }
}